/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.proyectounidad2_presentacion;

import com.mycompany.proyectounidad2_dominio.Estudiante;
import com.mycompany.proyectounidad2_dominio.TipoReaccion;
import com.mycompany.proyectounidad2_exceptions.NegocioException;
import com.mycompany.proyectounidad2_servicios.EstudianteService;
import com.mycompany.proyectounidad2_servicios.IEstudianteService;
import com.mycompany.proyectounidad2_servicios.IMatchService;
import com.mycompany.proyectounidad2_servicios.IReaccionService;
import com.mycompany.proyectounidad2_servicios.MatchService;
import com.mycompany.proyectounidad2_servicios.ReaccionService;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author Afgord
 */
public class frmExplorar extends javax.swing.JFrame {

    private Estudiante usuarioActual;
    private List<Estudiante> perfiles;
    private int indiceActual = 0;

    private IEstudianteService estudianteService = new EstudianteService();
    private IReaccionService reaccionService = new ReaccionService();
    private IMatchService matchService = new MatchService();

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(frmExplorar.class.getName());

    /**
     * Creates new form frmExplorar
     */
    public frmExplorar(Estudiante usuario) {
        initComponents();
        this.usuarioActual = usuario;

        cargarPerfiles();
        mostrarPerfilActual();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lblNombre = new javax.swing.JLabel();
        lblCarrera = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDescripcion = new javax.swing.JTextArea();
        lblFoto = new javax.swing.JLabel();
        btnAnterior = new javax.swing.JButton();
        btnLike = new javax.swing.JButton();
        btnNoInteresa = new javax.swing.JButton();
        btnSiguiente = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("¡¡EXPLORAR TUS POSIBLES MATCHES!!");

        lblNombre.setText("Nombre: ");

        lblCarrera.setText("Carrera: ");

        jLabel4.setText("Descripción:");

        txtDescripcion.setColumns(20);
        txtDescripcion.setRows(5);
        jScrollPane1.setViewportView(txtDescripcion);

        lblFoto.setText("Foto:");

        btnAnterior.setText("Anterior");
        btnAnterior.addActionListener(this::btnAnteriorActionPerformed);

        btnLike.setText("LIKE");
        btnLike.addActionListener(this::btnLikeActionPerformed);

        btnNoInteresa.setText("NO ME INTERESA");
        btnNoInteresa.addActionListener(this::btnNoInteresaActionPerformed);

        btnSiguiente.setText("Siguiente");
        btnSiguiente.addActionListener(this::btnSiguienteActionPerformed);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btnAnterior)
                        .addGap(18, 18, 18)
                        .addComponent(btnLike)
                        .addGap(18, 18, 18)
                        .addComponent(btnNoInteresa)
                        .addGap(18, 18, 18)
                        .addComponent(btnSiguiente)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 404, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(lblCarrera))
                        .addContainerGap(26, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lblNombre)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblFoto)
                        .addGap(126, 126, 126))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombre)
                    .addComponent(lblFoto))
                .addGap(18, 18, 18)
                .addComponent(lblCarrera)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAnterior)
                    .addComponent(btnLike)
                    .addComponent(btnNoInteresa)
                    .addComponent(btnSiguiente))
                .addContainerGap(50, Short.MAX_VALUE))
        );

        btnSalir.setText("Regresar");
        btnSalir.addActionListener(this::btnSalirActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(btnSalir)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(btnSalir))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAnteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnteriorActionPerformed
        if (indiceActual > 0) {
            indiceActual--;
            mostrarPerfilActual();
        }
    }//GEN-LAST:event_btnAnteriorActionPerformed

    private void btnNoInteresaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNoInteresaActionPerformed
        reaccionar(TipoReaccion.NO_INTERESA);
    }//GEN-LAST:event_btnNoInteresaActionPerformed

    private void btnSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSiguienteActionPerformed
        indiceActual++;
        mostrarPerfilActual();
    }//GEN-LAST:event_btnSiguienteActionPerformed

    private void btnLikeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLikeActionPerformed
        reaccionar(TipoReaccion.LIKE);
    }//GEN-LAST:event_btnLikeActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        frmPrincipal frm = new frmPrincipal(usuarioActual);
        frm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAnterior;
    private javax.swing.JButton btnLike;
    private javax.swing.JButton btnNoInteresa;
    private javax.swing.JButton btnSalir;
    private javax.swing.JButton btnSiguiente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCarrera;
    private javax.swing.JLabel lblFoto;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JTextArea txtDescripcion;
    // End of variables declaration//GEN-END:variables

    private void cargarPerfiles() {
        perfiles = estudianteService.explorarPerfiles(usuarioActual.getId());

        if (perfiles == null || perfiles.isEmpty()) {
            JOptionPane.showMessageDialog(this, "No hay perfiles disponibles.");
        }
    }

    private void mostrarPerfilActual() {
        if (perfiles == null || perfiles.isEmpty()) {
            return;
        }

        if (indiceActual >= perfiles.size()) {
            JOptionPane.showMessageDialog(this, "Ya no hay más perfiles.");
            indiceActual = perfiles.size() - 1;
            return;
        }

        Estudiante e = perfiles.get(indiceActual);

        lblNombre.setText(e.getNombre() + " " + e.getApPat());
        lblCarrera.setText(e.getCarrera());
        txtDescripcion.setText(
                e.getDescripcion() != null ? e.getDescripcion() : ""
        );
    }

    private void reaccionar(TipoReaccion tipo) {
        if (perfiles == null || perfiles.isEmpty()) {
            return;
        }

        Estudiante receptor = perfiles.get(indiceActual);

        try {
            if (tipo == TipoReaccion.LIKE) {
                int matchesAntes = matchService
                        .obtenerMatchesDeEstudiante(usuarioActual.getId())
                        .size();

                reaccionService.registrarReaccion(usuarioActual, receptor, tipo);

                int matchesDespues = matchService
                        .obtenerMatchesDeEstudiante(usuarioActual.getId())
                        .size();

                if (matchesDespues > matchesAntes) {
                    JOptionPane.showMessageDialog(this, "💥 ¡ES UN MATCH!");
                } else {
                    JOptionPane.showMessageDialog(this, "Te gusta este perfil");
                }

            } else {
                reaccionService.registrarReaccion(usuarioActual, receptor, tipo);
            }

            indiceActual++;
            mostrarPerfilActual();

        } catch (NegocioException e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }

}
