/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.proyectounidad2_presentacion;

import com.mycompany.proyectounidad2_dominio.Estudiante;
import com.mycompany.proyectounidad2_dominio.Hobby;
import com.mycompany.proyectounidad2_exceptions.NegocioException;
import com.mycompany.proyectounidad2_servicios.EstudianteService;
import com.mycompany.proyectounidad2_servicios.HobbyService;
import com.mycompany.proyectounidad2_servicios.IEstudianteService;
import com.mycompany.proyectounidad2_servicios.IHobbyService;
import java.util.List;
import java.util.Set;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Afgord
 */
public class frmPerfil extends javax.swing.JFrame {

    private Estudiante usuarioActual;
    private IEstudianteService estudianteService = new EstudianteService();
    private IHobbyService hobbyService = new HobbyService();
    private String fotoSeleccionada;

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(frmPerfil.class.getName());

    /**
     * Creates new form frmPerfil
     */
    public frmPerfil(Estudiante usuario) {
        initComponents();
        txtDescripcion.setLineWrap(true);
        txtDescripcion.setWrapStyleWord(true);
        this.usuarioActual = usuario;
        this.fotoSeleccionada = usuario.getFotoPerfil();
        setLocationRelativeTo(null);

        lblFoto.setPreferredSize(new java.awt.Dimension(100, 100));
        lblFoto.setMinimumSize(new java.awt.Dimension(100, 100));
        lblFoto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblFoto.setVerticalAlignment(javax.swing.SwingConstants.CENTER);
        lblFoto.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblCambiarFoto.setText("<html><u>Cambiar foto</u></html>");
        lblCambiarFoto.setForeground(new java.awt.Color(0, 102, 204));
        lblCambiarFoto.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        btnDesactivar.setBackground(new java.awt.Color(220, 53, 69));
        btnDesactivar.setForeground(java.awt.Color.WHITE);

        ocultarColumnaIdHobbies();
        cargarDatosPerfil();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        lblFoto = new javax.swing.JLabel();
        lblCambiarFoto = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lblNombre = new javax.swing.JLabel();
        lblApPat = new javax.swing.JLabel();
        lblApMat = new javax.swing.JLabel();
        lblCorreo = new javax.swing.JLabel();
        lblCarrera = new javax.swing.JLabel();
        txtCarrera = new javax.swing.JTextField();
        lblDescripcion = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDescripcion = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        btnAgregarHobbie = new javax.swing.JButton();
        cmbHobbies = new javax.swing.JComboBox<>();
        btnNuevoHobby = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        btnGuardar = new javax.swing.JButton();
        btnRegresar = new javax.swing.JButton();
        btnDesactivar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblHobbies = new javax.swing.JTable();
        btnQuitarHobbie = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTitulo.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblTitulo.setText("PERFIL DE");

        lblFoto.setText("Foto");

        lblCambiarFoto.setText("Cambiar Foto");
        lblCambiarFoto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCambiarFotoMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(lblTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblFoto)
                .addGap(50, 50, 50))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblCambiarFoto)
                .addGap(23, 23, 23))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTitulo)
                    .addComponent(lblFoto))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(lblCambiarFoto)
                .addContainerGap())
        );

        lblNombre.setText("Nombre");

        lblApPat.setText("Apellido paterno");

        lblApMat.setText("Apellido materno");

        lblCorreo.setText("Correo institucional");

        lblCarrera.setText("Carrera: ");

        lblDescripcion.setText("Descripción: ");

        txtDescripcion.setColumns(20);
        txtDescripcion.setRows(5);
        jScrollPane1.setViewportView(txtDescripcion);

        jLabel1.setText("Hobbies/Intereses");

        btnAgregarHobbie.setText("Agregar");
        btnAgregarHobbie.addActionListener(this::btnAgregarHobbieActionPerformed);

        cmbHobbies.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbHobbies.addActionListener(this::cmbHobbiesActionPerformed);

        btnNuevoHobby.setText("Nuevo");
        btnNuevoHobby.addActionListener(this::btnNuevoHobbyActionPerformed);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lblCorreo)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lblNombre)
                        .addGap(117, 117, 117)
                        .addComponent(lblApPat)
                        .addGap(26, 26, 26)
                        .addComponent(lblApMat)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(lblCarrera)
                                .addGap(18, 18, 18)
                                .addComponent(txtCarrera))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(lblDescripcion)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane1))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cmbHobbies, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnAgregarHobbie)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnNuevoHobby)))
                        .addGap(13, 13, 13))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombre)
                    .addComponent(lblApPat)
                    .addComponent(lblApMat))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lblCorreo)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCarrera)
                            .addComponent(txtCarrera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblDescripcion)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(cmbHobbies, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnAgregarHobbie)
                        .addComponent(btnNuevoHobby)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(this::btnGuardarActionPerformed);

        btnRegresar.setText("Regresar");
        btnRegresar.addActionListener(this::btnRegresarActionPerformed);

        btnDesactivar.setText("ELIMINAR CUENTA");
        btnDesactivar.addActionListener(this::btnDesactivarActionPerformed);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(123, Short.MAX_VALUE)
                .addComponent(btnGuardar)
                .addGap(113, 113, 113)
                .addComponent(btnRegresar)
                .addGap(122, 122, 122))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(186, 186, 186)
                .addComponent(btnDesactivar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardar)
                    .addComponent(btnRegresar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addComponent(btnDesactivar)
                .addContainerGap())
        );

        tblHobbies.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "id", "Hobby"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Long.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tblHobbies);

        btnQuitarHobbie.setText("Eliminar");
        btnQuitarHobbie.addActionListener(this::btnQuitarHobbieActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnQuitarHobbie)
                        .addGap(9, 9, 9)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(btnQuitarHobbie)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        try {
            String carrera = txtCarrera.getText().trim();
            String descripcion = txtDescripcion.getText().trim();

            if (carrera.isBlank()) {
                JOptionPane.showMessageDialog(this, "La carrera no puede estar vacía.");
                return;
            }

//            String foto = usuarioActual.getFotoPerfil();
            String foto = (fotoSeleccionada == null || fotoSeleccionada.isBlank())
                    ? "default.jpg"
                    : fotoSeleccionada;

            if (foto == null || foto.isBlank()) {
                foto = "default.jpg";
            }

            Estudiante actualizado = estudianteService.actualizarPerfil(
                    usuarioActual.getId(),
                    carrera,
                    descripcion,
                    foto
            );

            this.usuarioActual = actualizado;
            this.fotoSeleccionada = actualizado.getFotoPerfil();

            JOptionPane.showMessageDialog(this, "Perfil actualizado correctamente.");
            cargarDatosPerfil();

        } catch (NegocioException e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        frmPrincipal frm = new frmPrincipal(usuarioActual);
        frm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnRegresarActionPerformed

    private void btnAgregarHobbieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarHobbieActionPerformed
        try {
            String seleccion = (String) cmbHobbies.getSelectedItem();

            if (seleccion == null || seleccion.isBlank()) {
                JOptionPane.showMessageDialog(this, "Selecciona un hobby.");
                return;
            }

            List<Hobby> hobbies = hobbyService.obtenerTodos();

            Hobby hobbySeleccionado = hobbies.stream()
                    .filter(h -> h.getNombre().equals(seleccion))
                    .findFirst()
                    .orElse(null);

            if (hobbySeleccionado != null) {
                boolean yaExiste = usuarioActual.getHobbies().stream()
                        .anyMatch(h -> h.getId().equals(hobbySeleccionado.getId()));

                if (yaExiste) {
                    JOptionPane.showMessageDialog(this, "Ya tienes este hobby.");
                    return;
                }

                estudianteService.agregarHobby(usuarioActual.getId(), hobbySeleccionado.getId());
                cargarHobbies();
                cargarComboHobbies();
            }

        } catch (NegocioException e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_btnAgregarHobbieActionPerformed

    private void btnQuitarHobbieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuitarHobbieActionPerformed
        int fila = tblHobbies.getSelectedRow();

        if (fila == -1) {
            JOptionPane.showMessageDialog(this, "Selecciona un hobby.");
            return;
        }

        //Long idHobby = (Long) tblHobbies.getValueAt(fila, 0);
        Long idHobby = (Long) tblHobbies.getModel().getValueAt(fila, 0);

        try {
            estudianteService.quitarHobby(usuarioActual.getId(), idHobby);
            cargarHobbies();
            cargarComboHobbies();
        } catch (NegocioException e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_btnQuitarHobbieActionPerformed

    private void cmbHobbiesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbHobbiesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbHobbiesActionPerformed

    private void btnNuevoHobbyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoHobbyActionPerformed
        try {
            String nombre = JOptionPane.showInputDialog(this, "Nombre del hobby:");

            if (nombre == null || nombre.isBlank()) {
                return;
            }

            Hobby nuevo = new Hobby(nombre.trim(), "");
            nuevo = hobbyService.registrarHobby(nuevo);

            estudianteService.agregarHobby(usuarioActual.getId(), nuevo.getId());

            JOptionPane.showMessageDialog(this, "Hobby agregado correctamente");

            cargarHobbies();
            cargarComboHobbies();

        } catch (NegocioException e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_btnNuevoHobbyActionPerformed

    private void lblCambiarFotoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCambiarFotoMouseClicked
        try {

            java.io.File carpetaInicial = new java.io.File(
                    "src/main/resources/imagenes/perfiles"
            );

            javax.swing.JFileChooser fileChooser = new javax.swing.JFileChooser(carpetaInicial);
            fileChooser.setDialogTitle("Seleccionar imagen");

            // Filtro solo imágenes
            fileChooser.setFileFilter(new javax.swing.filechooser.FileNameExtensionFilter(
                    "Imágenes", "jpg", "jpeg", "png"
            ));

            int resultado = fileChooser.showOpenDialog(this);

            if (resultado == javax.swing.JFileChooser.APPROVE_OPTION) {
                java.io.File archivo = fileChooser.getSelectedFile();

                String nombreArchivo = archivo.getName();

                // 🔥 IMPORTANTE: copiar a resources (simplificado)
                java.nio.file.Path destino = java.nio.file.Paths.get(
                        "src/main/resources/imagenes/perfiles/" + nombreArchivo
                );

                java.nio.file.Files.copy(
                        archivo.toPath(),
                        destino,
                        java.nio.file.StandardCopyOption.REPLACE_EXISTING
                );

//                usuarioActual.setFotoPerfil(nombreArchivo);
//                cargarFotoPerfil(nombreArchivo);
                fotoSeleccionada = nombreArchivo;
                cargarFotoPerfil(fotoSeleccionada);
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al cargar imagen");
        }
    }//GEN-LAST:event_lblCambiarFotoMouseClicked

    private void btnDesactivarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDesactivarActionPerformed
        int opcion = JOptionPane.showConfirmDialog(
                this,
                "¿Estás seguro de que deseas desactivar tu cuenta?",
                "Confirmar desactivación",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.WARNING_MESSAGE
        );

        if (opcion != JOptionPane.YES_OPTION) {
            return;
        }

        try {
            estudianteService.desactivarCuenta(usuarioActual.getId());

            JOptionPane.showMessageDialog(this,
                    "Tu cuenta ha sido desactivada correctamente.");

            frmLogin login = new frmLogin();
            login.setVisible(true);
            this.dispose();

        } catch (NegocioException e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_btnDesactivarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarHobbie;
    private javax.swing.JButton btnDesactivar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnNuevoHobby;
    private javax.swing.JButton btnQuitarHobbie;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JComboBox<String> cmbHobbies;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblApMat;
    private javax.swing.JLabel lblApPat;
    private javax.swing.JLabel lblCambiarFoto;
    private javax.swing.JLabel lblCarrera;
    private javax.swing.JLabel lblCorreo;
    private javax.swing.JLabel lblDescripcion;
    private javax.swing.JLabel lblFoto;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JTable tblHobbies;
    private javax.swing.JTextField txtCarrera;
    private javax.swing.JTextArea txtDescripcion;
    // End of variables declaration//GEN-END:variables

    private void cargarDatosPerfil() {
        try {
            Estudiante actualizado = estudianteService.buscarPorId(usuarioActual.getId());
            this.usuarioActual = actualizado;

            lblNombre.setText(actualizado.getNombre());
            lblApPat.setText(actualizado.getApPat());
            lblApMat.setText(actualizado.getApMat());
            lblCorreo.setText(actualizado.getCorreoInst());

            txtCarrera.setText(actualizado.getCarrera() != null ? actualizado.getCarrera() : "");
            txtDescripcion.setText(actualizado.getDescripcion() != null ? actualizado.getDescripcion() : "");

            lblTitulo.setText("PERFIL DE " + actualizado.getNombre());

            //cargarFotoPerfil(actualizado.getFotoPerfil());
            String fotoAMostrar = (fotoSeleccionada == null || fotoSeleccionada.isBlank())
                    ? actualizado.getFotoPerfil()
                    : fotoSeleccionada;

            cargarFotoPerfil(fotoAMostrar);
            cargarHobbies();
            cargarComboHobbies();

        } catch (NegocioException e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }

    private void cargarHobbies() {
        try {
            Estudiante e = estudianteService.buscarPorIdConHobbies(usuarioActual.getId());
            this.usuarioActual = e;

            DefaultTableModel modelo = (DefaultTableModel) tblHobbies.getModel();
            modelo.setRowCount(0);

            for (Hobby h : e.getHobbies()) {
                modelo.addRow(new Object[]{
                    h.getId(),
                    h.getNombre()
                });
            }

        } catch (NegocioException ex) {
            JOptionPane.showMessageDialog(this, "Error al cargar hobbies");
        }
    }

    private void cargarComboHobbies() {
        try {
            cmbHobbies.removeAllItems();

            List<Hobby> hobbies = hobbyService.obtenerTodos();

            Estudiante e = estudianteService.buscarPorIdConHobbies(usuarioActual.getId());
            this.usuarioActual = e;

            Set<Hobby> hobbiesUsuario = e.getHobbies();

            for (Hobby h : hobbies) {
                boolean yaLoTiene = hobbiesUsuario.stream()
                        .anyMatch(hu -> hu.getId().equals(h.getId()));

                if (!yaLoTiene) {
                    cmbHobbies.addItem(h.getNombre());
                }
            }

        } catch (NegocioException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
    }

    private void ocultarColumnaIdHobbies() {
        tblHobbies.getColumnModel().getColumn(0).setMinWidth(0);
        tblHobbies.getColumnModel().getColumn(0).setMaxWidth(0);
        tblHobbies.getColumnModel().getColumn(0).setPreferredWidth(0);
    }

    private void cargarFotoPerfil(String nombreArchivo) {
        try {
            if (nombreArchivo == null || nombreArchivo.isBlank()) {
                nombreArchivo = "default.jpg";
            }

            java.net.URL url = getClass().getResource("/imagenes/perfiles/" + nombreArchivo);

            if (url == null) {
                url = getClass().getResource("/imagenes/perfiles/default.jpg");
            }

            ImageIcon iconoOriginal = new ImageIcon(url);
            java.awt.Image imagenEscalada = iconoOriginal.getImage().getScaledInstance(
                    100, 100, java.awt.Image.SCALE_SMOOTH
            );

            lblFoto.setIcon(new ImageIcon(imagenEscalada));
            lblFoto.setText("");

        } catch (Exception e) {
            lblFoto.setIcon(null);
            lblFoto.setText("Sin foto");
        }

        lblFoto.revalidate();
        lblFoto.repaint();
        pack();
        setLocationRelativeTo(null);

    }

}
