/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.proyectounidad2_presentacion;

import com.mycompany.proyectounidad2_dominio.Estudiante;
import com.mycompany.proyectounidad2_exceptions.NegocioException;
import com.mycompany.proyectounidad2_servicios.IReaccionService;
import com.mycompany.proyectounidad2_servicios.ReaccionService;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Afgord
 */
public class frmPrincipal extends javax.swing.JFrame {

    private Estudiante usuarioActual;
    private IReaccionService reaccionService = new ReaccionService();

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(frmPrincipal.class.getName());

    /**
     * Creates new form frmPrincipal
     */
    public frmPrincipal(Estudiante usuario) {
        initComponents();
        this.usuarioActual = usuario;
        lblBienvenida.setText("Bienvenido, " + usuario.getNombre());
        setLocationRelativeTo(null);

        cargarFotoPerfil(usuario.getFotoPerfil());
        lblFoto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblFoto.setVerticalAlignment(javax.swing.SwingConstants.CENTER);
        lblFoto.setPreferredSize(new java.awt.Dimension(80, 80));
        lblFoto.setMinimumSize(new java.awt.Dimension(80, 80));

        lblNotificacion.setIcon(cargarIcono("/imagenes/iconos/notificacion.png"));
        lblNotificacion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        lblContador.setOpaque(true);
        lblContador.setBackground(new java.awt.Color(244, 67, 54));
        lblContador.setForeground(java.awt.Color.WHITE);
        lblContador.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblContador.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.WHITE));
        lblContador.setPreferredSize(new java.awt.Dimension(20, 20));

        btnExplorar.setIcon(cargarIcono("/imagenes/iconos/explorar.png"));
        btnExplorar.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnExplorar.setIconTextGap(15);

        btnMatches.setIcon(cargarIcono("/imagenes/iconos/matches.jpg"));
        btnMatches.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnMatches.setIconTextGap(15);

        btnPerfil.setIcon(cargarIcono("/imagenes/iconos/perfil.jpg"));
        btnPerfil.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnPerfil.setIconTextGap(15);

        btnCerrarSesion.setIcon(cargarIcono("/imagenes/iconos/logout.png"));
        btnCerrarSesion.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnCerrarSesion.setIconTextGap(15);

        cargarLikesPendientes();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblBienvenida = new javax.swing.JLabel();
        lblFoto = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btnExplorar = new javax.swing.JButton();
        btnMatches = new javax.swing.JButton();
        btnPerfil = new javax.swing.JButton();
        btnCerrarSesion = new javax.swing.JButton();
        lblNotificacion = new javax.swing.JLabel();
        lblContador = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblBienvenida.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblBienvenida.setText("Bienvenido,");

        lblFoto.setText("Foto");
        lblFoto.setMaximumSize(new java.awt.Dimension(80, 80));
        lblFoto.setMinimumSize(new java.awt.Dimension(100, 100));
        lblFoto.setOpaque(true);
        lblFoto.setPreferredSize(new java.awt.Dimension(80, 80));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(lblBienvenida, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblFoto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBienvenida)
                    .addComponent(lblFoto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19))
        );

        btnExplorar.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnExplorar.setText("Explorar Perfiles");
        btnExplorar.addActionListener(this::btnExplorarActionPerformed);

        btnMatches.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnMatches.setText("Mis matches");
        btnMatches.addActionListener(this::btnMatchesActionPerformed);

        btnPerfil.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnPerfil.setText("Mi perfil");
        btnPerfil.addActionListener(this::btnPerfilActionPerformed);

        btnCerrarSesion.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnCerrarSesion.setText("Cerrar Sesión");
        btnCerrarSesion.addActionListener(this::btnCerrarSesionActionPerformed);

        lblNotificacion.setText("Img");
        lblNotificacion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblNotificacionMouseClicked(evt);
            }
        });

        lblContador.setText("0");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblNotificacion)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(btnExplorar, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnMatches, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnPerfil, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnCerrarSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblContador)
                .addGap(23, 23, 23))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNotificacion)
                    .addComponent(lblContador))
                .addGap(18, 18, 18)
                .addComponent(btnExplorar)
                .addGap(18, 18, 18)
                .addComponent(btnMatches)
                .addGap(18, 18, 18)
                .addComponent(btnPerfil)
                .addGap(18, 18, 18)
                .addComponent(btnCerrarSesion)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 414, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMatchesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMatchesActionPerformed
        frmMatches frm = new frmMatches(usuarioActual);
        frm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnMatchesActionPerformed

    private void btnExplorarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExplorarActionPerformed
        frmExplorar frm = new frmExplorar(usuarioActual);
        frm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnExplorarActionPerformed

    private void btnPerfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPerfilActionPerformed
        frmPerfil frm = new frmPerfil(usuarioActual);
        frm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnPerfilActionPerformed

    private void btnCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarSesionActionPerformed
        int opcion = JOptionPane.showConfirmDialog(
                this,
                "¿Deseas cerrar sesión?",
                "Cerrar sesión",
                JOptionPane.YES_NO_OPTION
        );

        if (opcion == JOptionPane.YES_OPTION) {
            frmLogin login = new frmLogin();
            login.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_btnCerrarSesionActionPerformed

    private void lblNotificacionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblNotificacionMouseClicked
        try {
            List<Estudiante> pendientes = reaccionService.obtenerLikesPendientes(usuarioActual.getId());

            if (pendientes.isEmpty()) {
                JOptionPane.showMessageDialog(this, "No tienes likes pendientes.");
                return;
            }

            String[] opciones = pendientes.stream()
                    .map(e -> e.getNombre() + " " + e.getApPat())
                    .toArray(String[]::new);

            String seleccion = (String) JOptionPane.showInputDialog(
                    this,
                    "Selecciona un alumno para responder su like:",
                    "Likes pendientes",
                    JOptionPane.QUESTION_MESSAGE,
                    null,
                    opciones,
                    opciones[0]
            );

            if (seleccion == null) {
                return;
            }

            Estudiante objetivo = pendientes.stream()
                    .filter(e -> (e.getNombre() + " " + e.getApPat()).equals(seleccion))
                    .findFirst()
                    .orElse(null);

            if (objetivo != null) {
                frmExplorar frm = new frmExplorar(usuarioActual, objetivo.getId());
                frm.setVisible(true);
                this.dispose();
            }

        } catch (NegocioException e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_lblNotificacionMouseClicked

    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCerrarSesion;
    private javax.swing.JButton btnExplorar;
    private javax.swing.JButton btnMatches;
    private javax.swing.JButton btnPerfil;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblBienvenida;
    private javax.swing.JLabel lblContador;
    private javax.swing.JLabel lblFoto;
    private javax.swing.JLabel lblNotificacion;
    // End of variables declaration//GEN-END:variables

    private void cargarFotoPerfil(String nombreArchivo) {
        try {
            if (nombreArchivo == null || nombreArchivo.isBlank()) {
                nombreArchivo = "default.jpg";
            }

            java.net.URL url = getClass().getResource("/imagenes/perfiles/" + nombreArchivo);

            if (url == null) {
                url = getClass().getResource("/imagenes/perfiles/default.jpg");
            }

            ImageIcon iconoOriginal = new ImageIcon(url);
            java.awt.Image imagenEscalada = iconoOriginal.getImage().getScaledInstance(
                    100, 100, java.awt.Image.SCALE_SMOOTH
            );

            lblFoto.setIcon(new ImageIcon(imagenEscalada));
            lblFoto.setText("");

        } catch (Exception e) {
            lblFoto.setIcon(null);
            lblFoto.setText("Sin foto");
        }

        lblFoto.revalidate();
        lblFoto.repaint();
        pack();
        setLocationRelativeTo(null);

    }

    private void cargarLikesPendientes() {
        try {
            int cantidad = reaccionService.contarLikesPendientes(usuarioActual.getId());

            lblContador.setText(String.valueOf(cantidad));
            lblContador.setVisible(cantidad > 0);

        } catch (Exception e) {
            lblContador.setText("0");
            lblContador.setVisible(false);
        }
        lblContador.revalidate();
        lblContador.repaint();
        pack();
        setLocationRelativeTo(null);

    }

    private ImageIcon cargarIcono(String ruta) {
        ImageIcon icono = new ImageIcon(getClass().getResource(ruta));
        java.awt.Image img = icono.getImage().getScaledInstance(32, 32, java.awt.Image.SCALE_SMOOTH);
        return new ImageIcon(img);
    }
}
